dist: focal

services:
  - xvfb

language: python

python:
  - "3.9"

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - sudo apt-get update
  - sudo apt-get install openscad
  - sudo apt-get install antlr4

script:
    python -m pytest

after_success:
  - coveralls
