language: python

services:
    - xvfb

branches:
    only:
        - master

python:
    - "3.9"

install:
    - pip install -r requirements.txt
    - pip install coveralls

script:
    - make test

after_success:
    - coveralls
