language: python

python:
  - "3.9"

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - sudo apt-get update
  - sudo apt-get install openscad-mcad

script:
    python -m pytest

after_success:
  - coveralls
