language: python

python:
  - "3.9"

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - sudo add-apt-repository -y ppa:openscad/releases
  - sudo add-apt-repository update
  - sudo apt install openscad

script:
    python -m pytest

after_success:
  - coveralls
