image:
- macos
- Visual Studio 2019
- Ubuntu

stack: python 3

environment:
  PY_DIR: C:\Python39-x64

clone_depth: 25

build: off

init:
- cmd: set PATH=%PY_DIR%;%PY_DIR%\Scripts;%PATH%
- cmd: set PATH="C:\Program Files\openscad";%PATH%

install:
- python --version
- python -m pip install --upgrade pip
- python -m pip install -r requirements.txt
- choco install openscad

test_script:
  - python -m pytest
