image:
  - Visual Studio 2019

for:
-
  matrix:
    only:
      - image: Visual Studio 2019
  build: off
  environment:
    PYTHON: "C:\\Python39-x64"
  init:
    - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  install:
    - python --version
    - python -m pip install --upgrade pip
    - python -m pip install -r requirements.txt
  test_script:
    - pytest

