..  |CI|    replace::   *Continuous Integration*

..	|GH|	replace:: *GitHub*
..	_GH:	https://github.com/

..	_Git:	https://git-scm.com/

..  _Linus Torvalds:    https://en.wikipedia.org/wiki/Linus_Torvalds
..  |MM|    replace::   *Math-Magik*
..  _MM:    https://github.com/rblack42/math-magik

..  _OpenSCAD:          https://openscad.org/

..  |OS|    replace::   *Open Source*

..	|PY|	replace::	*Python*
..	_PY:	https://www.python.org/

..  _PyCharm:           https://jetbrains.com/pycharm/

..  |RST|   replace:: *reStructuredText*

..  _Sphinx:            https://sphinx-doc.org/

..  _tkinter:           https://docs.python.org/3/library/tkinter.html
