..  _Ludwig Prandtl:    https://en.wikipedia.org/wiki/Ludwig_Prandtl
..  _Justin Lin:        https://openhome.cc/eGossip/OpenSCAD/
..  |LPP|               replace:: Limited Pennyplane

..  |HAFFA|             replace:: Heart of America Free Flight Association
..  _HAFFA:             https://kcfreeflight.org/

..  |AMA|               replace::  Academy of Model Aeronautics
..  _AMA:               https://www.modelaircraft.org/
..  _AMA Rule Book:     https://www.modelaircraft.org/sites/default/files/Indoor_Free_Flight_2019-2021.pdf

..  |NFFS|              replace:: National Free Flight Society
..  _NFFS:              https://freeflight.org/

..  |ECIM|               replace:: East Coast Indoor Modelers
..  _ECIM:               http://www.ecim.club/

..  |INAV|              replace:: "Indoor News and Views"
..  INAV:               https://indoornewsandviews.com/

..  _Sphinx:            https://www.sphinx-doc.org
..  _OpenSCAD:          https://www.openscad.org/
..  _reStructuredText:  https://docutils.sourceforge.io/rst.html
..  _Jupyter:           https://jupyter.org/
..  _Github:            https://github.com/
..  _SymPy:             https://www.sympy.org/en/index.html
..  _Python:            https://www.python.org/

..  _travis-ci:         https;//travis-ci.com/

..  |TDD|               replace:: *Test Driven Development*
