on:
  push:
    branches:
      - master
  pull_request:

jobs:
  pytest-linux:
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - run: pip install -r requirements.txt
      - run: pip install tk-dev python3-tk
      - name: run headless tests
        uses: GabrielBB/xvfb-action@v1
        with:
            run: python3 -m pytest -vvv
