on:
  push:
    branches:
      - master
  pull_request:

jobs:
  pytest-linux:
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - run: pip install -r requirements.txt
        run: pip install tk-dev python3-tk
        run: |
            disp:12
            screen:0
            geom=640x480x24
            exec Xvfb $disp -screen $screen $geom 2>/tmp/Xvfb.log &
            export DISPLAY=:12
            python3 -m pytest -vvvv
        run: kill $!
